[package]
name = "glotitude_hq"
version = "0.1.0"
authors = ["ltoshchev <ltoshchev@yandex-team.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctchi = "0.5.0"